---
# tasks file for adots

- name: "Deploy {{ adots_current_package }} dotfiles"
  ansible.posix.synchronize:
    #
    src: "{{ adots_role_root_folder }}/files/"
    # structure in src folder should be the desired structure on the dest
    dest: ~/.adots/
    #
    archive: false
    checksum: yes
    compress: true
    # Copy symlinks as the item that they point to (the referent) is copied, rather than the symlink.
    copy_links: true
    # Copy symlinks as symlinks.
    # links: false
    delete: false
    mode: push
    # this sets owner:group to the copying user
    owner: false
    group: false
    perms: "{{ adots_deploy_keep_permissions | bool }}"
    recursive: true
    ssh_connection_multiplexing: true
    rsync_opts:
      - "--mkpath"
