---
# Backup Dotfiles

# tasks file for dotfiles
- name:  Create Dotfiles Local Backup Folder
  ansible.builtin.file:
    path: "files/backup/{{ inventory_hostname }}/{{ ansible_user }}"
    state: directory
#    owner: "{{ lookup('env', 'USER') }}"
#    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'
#  become: yes
#  become_user: "{{ lookup('env', 'USER') }}"
  delegate_to: "{{ inventory_hostname }}"

- name: Backup Category Packages (all files that are defined in the dotfile_packages.package.'backup_paths' var)
  include_tasks: backup-dotfile-package.yml
  loop: "{{ dotfile_packages }}"
  loop_control:
    loop_var: dot_package
  when: dot_package.type in dotfiles_tags

- name: Backup Extra Packages (all files that are defined in the dotfile_packages.package.'backup_paths' var)
  include_tasks: backup-dotfile-package.yml
  loop: "{{  dotfiles_extra_packages if dotfiles_extra_packages is iterable and dotfiles_extra_packages is not string else [] }}"
  loop_control:
    loop_var: dot_package
