---
# tasks file for adots

- name: "Install adots dependencies"
  ansible.builtin.include_tasks: adots_install.yml



#- name: Set up the configured shells for users
#  user:
#    name: "{{ item.name }}"
#    shell: "{{ item.shell | default('/bin/bash') }}"
#  loop: "{{ users_accounts }}"
#  when: ansible_user_id == 'root'



#- name: "{{ ansible_user_id }} Disable Starship if requested"
#  ansible.builtin.file:
#    path:
#      - .bashrc.d/98.starship.bashrc
#      - .config/fish/conf.d/98.starship.fish
#      - .zsh/96.prompt.starship.zsh
#      - bin/starship
#    state: absent
#  when: disable_starship | default(false)
