---
# tasks file for adots

- name: "{{ adots_current_package }} : Fetch Make sure destination dir exists "
  file:
    path: "{{ adots_backup_path }}/{{ inventory_hostname }}/{{ ansible_user }}/{{ item | dirname }}"
    state: directory
  loop: "{{ adots_found_backup_paths }}"
  when: adots_backup_method == 'fetch'

- name: "{{ adots_current_package }} : Fetch Backup dotfiles "
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: "{{ adots_backup_path }}/{{ inventory_hostname }}/{{ ansible_user }}/{{ item }}"
    fail_on_missing: false
  loop: "{{ adots_found_backup_paths }}"
  when: adots_backup_method == 'fetch'
