---
# tasks file for adots

- name: "{{ adots_current_package }} : Collecting backups paths"
  local_action:  "ansible.builtin.command find {{ adots_role_root_folder }}/files/ -type f -printf '%P\n'"
  register: _adots_local_found_backup_paths

- name: "{{ adots_current_package }} : Cleaning backups paths"
  ansible.builtin.set_fact:
    adots_found_backup_paths: "{{ _adots_local_found_backup_paths['stdout_lines'] | reject('==', '') | list }}"
    cacheable: false

- name: "{{ adots_current_package }} : Backup dotfiles to target: {{ adots_backup_path }}/{{ inventory_hostname }}/{{ ansible_user }}"
  ansible.builtin.debug:
    msg: "{{ adots_found_backup_paths }}"

- name: "{{ adots_current_package }} : Rsync Backup dotfiles"
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "{{ adots_backup_path }}/{{ inventory_hostname }}/{{ ansible_user }}/{{ item }}"
    archive: true
    checksum: true
    compress: true
    delete: false
    mode: pull
    recursive: true
    owner: false
    group: false
    perms: false
    rsync_opts:
      - "--mkpath"
  ignore_errors: yes
  loop: "{{ adots_found_backup_paths }}"
  when: adots_backup_method == 'synchronize'

- name: "{{ adots_current_package }} : Fetch Make sure destination dir exists "
  file:
    path: "{{ adots_backup_path }}/{{ inventory_hostname }}/{{ ansible_user }}/{{ item | dirname }}"
    state: directory
  loop: "{{ adots_found_backup_paths }}"
  when: adots_backup_method == 'fetch'

- name: "{{ adots_current_package }} : Fetch Backup dotfiles "
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: "{{ adots_backup_path }}/{{ inventory_hostname }}/{{ ansible_user }}/{{ item }}"
    fail_on_missing: false
  loop: "{{ adots_found_backup_paths }}"
  when: adots_backup_method == 'fetch'
