---
# tasks file for adots

- name: "{{ adots_current_package }} : Rsync Backup dotfiles"
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "{{ adots_backup_path }}/{{ inventory_hostname }}/{{ ansible_user }}/{{ item }}"
    archive: true
    checksum: true
    compress: true
    delete: false
    mode: pull
    recursive: true
    owner: false
    group: false
    perms: false
    rsync_opts:
      - "--mkpath"
  ignore_errors: yes
  loop: "{{ adots_found_backup_paths }}"
  when: adots_backup_method == 'synchronize'

- name: "{{ adots_current_package }} : Rsync Backup dotfiles"
  ansible.posix.synchronize:
    src: "{{ item }}"
    dest: "{{ adots_backup_path }}/{{ inventory_hostname }}/{{ ansible_user }}/{{ item }}"
    archive: true
    checksum: true
    compress: true
    delete: false
    mode: pull
    recursive: true
    owner: false
    group: false
    perms: false
    rsync_opts:
      - "--mkpath"
  ignore_errors: yes
  loop: "{{ adots_found_backup_paths }}"
  when: (adots.backup_paths is defined and backup_paths | length > 0
