---
# tasks file for adots

- name: "Install {{ ansible_parent_role_names }} packages AUR"
  ansible.builtin.debug:
    msg: "Not implemented yet {{ adots.packages.aur }}"
  when: adots.packages.aur and adots.packages.aur|length > 0
